<a href="https://colab.research.google.com/github/jaipriyap6-code/codsoft_tasks/blob/main/CODSOFT_Task2_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
ds = pd.read_csv('/content/superstore_sales_eda.csv')
ds

,Order_ID,Order_Date,Customer_Name,Segment,City,State,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,ORD0019,2023-01-09,Rohit,Consumer,Jaipur,Rajasthan,Technology,Printers,Printers Product 3,1358.52,1,0.00,310.31
1,ORD0186,2023-01-12,Manoj,Consumer,Chennai,Tamil Nadu,Office Supplies,Storage,Storage Product 14,944.87,4,0.10,168.08
2,ORD0166,2023-01-12,Amit,Corporate,Jaipur,Rajasthan,Office Supplies,Binders,Binders Product 14,163.68,5,0.00,11.19
3,ORD0138,2023-01-12,Meena,Consumer,Bangalore,Karnataka,Office Supplies,Paper,Paper Product 20,553.59,5,0.00,34.15
4,ORD0048,2023-01-12,Meena,Consumer,Jaipur,Rajasthan,Office Supplies,Binders,Binders Product 16,367.50,1,0.15,36.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,ORD0116,2024-12-05,Asha,Consumer,Mumbai,Maharashtra,Office Supplies,Binders,Binders Product 18,929.61,4,0.05,167.52
196,ORD0156,2024-12-08,Amit,Consumer,Mumbai,Maharashtra,Office Supplies,Paper,Paper Product 17,1075.15,3,0.10,98.65
197,ORD0017,2024-12-11,Lakshmi,Corporate,Hyderabad,Telangana,Technology,Laptops,Laptops Product 9,3129.65,3,0.15,537.69
198,ORD0122,2024-12-26,Priya,Consumer,Kolkata,West Bengal,Office Supplies,Paper,Paper Product 24,828.97,4,0.10,55.99
199,ORD0028,2024-12-27,Ramesh,Corporate,Mumbai,Maharashtra,Furniture,Chairs,Chairs Product 25,1984.90,3,0.05,218.26

In [ ]:
ds.head(200)

,Order_ID,Order_Date,Customer_Name,Segment,City,State,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,ORD0019,2023-01-09,Rohit,Consumer,Jaipur,Rajasthan,Technology,Printers,Printers Product 3,1358.52,1,0.00,310.31
1,ORD0186,2023-01-12,Manoj,Consumer,Chennai,Tamil Nadu,Office Supplies,Storage,Storage Product 14,944.87,4,0.10,168.08
2,ORD0166,2023-01-12,Amit,Corporate,Jaipur,Rajasthan,Office Supplies,Binders,Binders Product 14,163.68,5,0.00,11.19
3,ORD0138,2023-01-12,Meena,Consumer,Bangalore,Karnataka,Office Supplies,Paper,Paper Product 20,553.59,5,0.00,34.15
4,ORD0048,2023-01-12,Meena,Consumer,Jaipur,Rajasthan,Office Supplies,Binders,Binders Product 16,367.50,1,0.15,36.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,ORD0116,2024-12-05,Asha,Consumer,Mumbai,Maharashtra,Office Supplies,Binders,Binders Product 18,929.61,4,0.05,167.52
196,ORD0156,2024-12-08,Amit,Consumer,Mumbai,Maharashtra,Office Supplies,Paper,Paper Product 17,1075.15,3,0.10,98.65
197,ORD0017,2024-12-11,Lakshmi,Corporate,Hyderabad,Telangana,Technology,Laptops,Laptops Product 9,3129.65,3,0.15,537.69
198,ORD0122,2024-12-26,Priya,Consumer,Kolkata,West Bengal,Office Supplies,Paper,Paper Product 24,828.97,4,0.10,55.99
199,ORD0028,2024-12-27,Ramesh,Corporate,Mumbai,Maharashtra,Furniture,Chairs,Chairs Product 25,1984.90,3,0.05,218.26

Check the dataset size

In [ ]:
ds.shape

(200, 13)

In [ ]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       200 non-null    object
 1   Order_Date     200 non-null    object
 2   Customer_Name  200 non-null    object
 3   Segment        200 non-null    object
 4   City           200 non-null    object
 5   State          200 non-null    object
 6   Category       200 non-null    object
 7   Sub_Category   200 non-null    object
 8   Product_Name   200 non-null    object
 9   Sales          200 non-null    float64
 10  Quantity       200 non-null    int64
 11  Discount       200 non-null    float64
 12  Profit         200 non-null    float64
dtypes: float64(3), int64(1), object(9)
memory usage: 20.4+ KB

In [ ]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       200 non-null    object
 1   Order_Date     200 non-null    object
 2   Customer_Name  200 non-null    object
 3   Segment        200 non-null    object
 4   City           200 non-null    object
 5   State          200 non-null    object
 6   Category       200 non-null    object
 7   Sub_Category   200 non-null    object
 8   Product_Name   200 non-null    object
 9   Sales          200 non-null    float64
 10  Quantity       200 non-null    int64
 11  Discount       200 non-null    float64
 12  Profit         200 non-null    float64
dtypes: float64(3), int64(1), object(9)
memory usage: 20.4+ KB

Descriptive Statistics

In [ ]:
ds.describe()

             Sales    Quantity    Discount      Profit
count   200.000000  200.000000  200.000000  200.000000
mean   1391.185200    5.305000    0.108000  153.660900
std    1093.538396    2.931714    0.076421  162.605753
min      34.340000    1.000000    0.000000 -310.430000
25%     532.822500    3.000000    0.050000   40.080000
50%    1019.590000    5.000000    0.100000   99.215000
75%    2184.387500    8.000000    0.150000  209.805000
max    4488.340000   10.000000    0.300000  909.440000

Check missing values

In [ ]:
ds.isnull().sum()

Order_ID         0
Order_Date       0
Customer_Name    0
Segment          0
City             0
State            0
Category         0
Sub_Category     0
Product_Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [ ]:
ds.duplicated().sum()

np.int64(0)

Find total Sales and Profit

In [ ]:
print("Total Sales:", ds['Sales'].sum())
print("Total Profit:", ds['Profit'].sum())

Total Sales: 278237.04000000004
Total Profit: 30732.18

Find average Sales and Profit

In [ ]:
print("Average Sales:", ds['Sales'].mean())
print("Average Profit:", ds['Profit'].mean())

Average Sales: 1391.1852000000001
Average Profit: 153.6609

Find highest and lowest Sales

In [ ]:
print("Highest Sales:", ds['Sales'].max())
print("Lowest Sales:", ds['Sales'].min())

Highest Sales: 4488.34
Lowest Sales: 34.34

Which category generates the highest sales

In [ ]:
ds.groupby('Category')['Sales'].sum()

Category
Furniture           97352.42
Office Supplies     46495.95
Technology         134388.67
Name: Sales, dtype: float64

In [ ]:
ds.groupby('Category')['Sales'].sum().sort_values(ascending=False)

Category
Technology         134388.67
Furniture           97352.42
Office Supplies     46495.95
Name: Sales, dtype: float64

Which category generates the highest profit?

In [ ]:
ds.groupby('Category')['Profit'].sum().sort_values(ascending=False)

Category
Technology         14469.86
Furniture          11278.16
Office Supplies     4984.16
Name: Profit, dtype: float64

Which customer segment generates the most sales?

In [ ]:
ds.groupby('Segment')['Sales'].sum().sort_values(ascending=False)

Segment
Consumer       160935.47
Corporate       84573.29
Home Office     32728.28
Name: Sales, dtype: float64

Profit by Customer Segment

In [ ]:
ds.groupby('Segment')['Profit'].sum().sort_values(ascending=False)

Segment
Consumer       15785.42
Corporate      11308.71
Home Office     3638.05
Name: Profit, dtype: float64

which city generates the most sales.

In [ ]:
ds.groupby('City')['Sales'].sum().sort_values(ascending=False)

City
Chennai      39696.54
Mumbai       35268.07
Jaipur       35227.55
Pune         30468.32
Bangalore    29842.24
Kochi        29249.53
Delhi        26185.25
Hyderabad    22906.34
Ahmedabad    18240.13
Kolkata      11153.07
Name: Sales, dtype: float64

Sales by State

In [ ]:
ds.groupby('State')['Sales'].sum().sort_values(ascending=False)

State
Maharashtra    65736.39
Tamil Nadu     39696.54
Rajasthan      35227.55
Karnataka      29842.24
Kerala         29249.53
Delhi          26185.25
Telangana      22906.34
Gujarat        18240.13
West Bengal    11153.07
Name: Sales, dtype: float64

Convert Order Date

In [ ]:
ds['Order_Date'] = pd.to_datetime(ds['Order_Date'])

In [ ]:
ds['Order_Date'].dtype

dtype('<M8[ns]')

Analyze sales over time

In [ ]:
ds['Year'] = ds['Order_Date'].dt.year

In [ ]:
ds.groupby('Year')['Sales'].sum()

Year
2023    124768.09
2024    153468.95
Name: Sales, dtype: float64

Check relationship between Sales and Profit

In [ ]:
ds[['Sales', 'Profit']].corr()

           Sales    Profit
Sales   1.000000  0.692179
Profit  0.692179  1.000000

Find the most profitable products

In [ ]:
ds.groupby('Product_Name')['Profit'].sum().sort_values(ascending=False).head(10)

Product_Name
Printers Product 28       1229.45
Accessories Product 25    1032.62
Accessories Product 30     909.44
Bookcases Product 14       745.64
Chairs Product 3           745.57
Printers Product 18        728.31
Chairs Product 25          624.90
Printers Product 27        596.39
Furnishings Product 9      576.34
Laptops Product 9          537.69
Name: Profit, dtype: float64

Find the highest-selling products

In [ ]:
ds.groupby('Product_Name')['Sales'].sum().sort_values(ascending=False).head(10)

Product_Name
Chairs Product 3          7918.62
Printers Product 28       7729.77
Accessories Product 25    6972.34
Printers Product 18       5807.42
Chairs Product 25         5106.19
Bookcases Product 14      5023.44
Bookcases Product 23      4538.80
Accessories Product 30    4488.34
Printers Product 7        4485.96
Laptops Product 30        4457.33
Name: Sales, dtype: float64

Check the relationship between Discount and Profit

In [ ]:
ds[['Discount', 'Profit']].corr()

          Discount   Profit
Discount   1.00000 -0.19478
Profit    -0.19478  1.00000