<a href="https://colab.research.google.com/github/jaipriyap6-code/codsoft_tasks/blob/main/CODSOFT_Task1_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
emp=pd.read_csv('/content/employee_salary_dataset.csv')
emp

,Employee_ID,Name,Age,Gender,Department,Salary,Joining_Date,City
0,E001,Rahul,25.0,Male,IT,45000,2022-01-15,Bangalore
1,E002,Priya,28.0,Female,HR,52000,2021-03-20,Chennai
2,E003,Arun,31.0,Male,it,60000,2020-07-11,Bangalore
3,E004,Divya,NaN,Female,Finance,55000,2022-05-18,Hyderabad
4,E005,Kiran,26.0,Male,IT,NaN,2023-02-10,Mumbai
5,E006,Sneha,29.0,Female,HR,48000,2021-09-05,Chennai
6,E007,Vikram,35.0,Male,Finance,72000,2019-11-22,Pune
7,E008,Anjali,27.0,Female,IT,58000,2022-08-14,Bangalore
8,E009,Rohit,33.0,Male,Sales,65000,2020-04-17,Delhi
9,E010,Meena,30.0,Female,sales,61000,2021-06-25,NaN
10,E011,Suresh,24.0,Male,IT,42000,2023-01-09,Bangalore
11,E012,Pooja,32.0,Female,Finance,68000,2020-12-01,Hyderabad
12,E013,Amit,29.0,Male,HR,50000,2022-03-12,Mumbai
13,E014,Neha,26.0,Female,IT,47000,2023-04-21,Pune
14,E015,Vijay,38.0,Male,Sales,85000,2018-10-30,Delhi
15,E016,Kavya,27.0,Female,Finance,59000,2022-07-19,Chennai
16,E017,Manoj,34.0,Male,it,71000,2019-05-16,Bangalore
17,E018,Asha,23.0,Female,HR,43000,2023-06-08,Hyderabad
18,E019,Ramesh,41.0,Male,Finance,90000,2017-02-14,Pune
19,E020,Lakshmi,36.0,Female,sales,76000,2019-08-27,Chennai
20,E021,Deepak,28.0,Male,IT,54000,2021-11-03,Mumbai
21,E022,Nisha,31.0,Female,HR,57000,2020-09-15,Bangalore
22,E023,Karthik,30.0,Male,Finance,63000,2021-01-20,Hyderabad
23,E024,Swathi,25.0,Female,IT,46000,2023-03-11,Pune
24,E025,Ajay,37.0,Male,Sales,79000,2019-12-05,Delhi
25,E026,Riya,29.0,Female,Finance,62000,2021-05-29,Chennai
26,E027,Naveen,33.0,Male,HR,59000,2020-02-18,Mumbai
27,E028,Shalini,27.0,Female,IT,51000,2022-10-07,Bangalore
28,E029,Ganesh,39.0,Male,Finance,82000,2018-06-13,Pune
29,E030,Isha,24.0,female,Sales,44000,2023-07-02,Delhi
30,E031,Ravi,32.0,Male,IT,67000,2020-08-24,Bangalore
31,E032,Tina,30.0,Female,HR,56000,2021-10-19,Hyderabad
32,E033,Mohan,35.0,Male,Finance,74000,2019-03-09,Chennai
33,E034,Sonia,28.0,Female,IT,53000,2022-11-16,Mumbai
34,E035,Hari,42.0,Male,Sales,92000,2016-12-21,Delhi
35,E036,Rekha,26.0,Female,Finance,58000,2023-01-30,Pune
36,E037,Surya,31.0,Male,IT,64000,2020-06-05,Bangalore
37,E038,Maya,34.0,Female,HR,69000,2019-09-12,Chennai
38,E039,Nitin,29.0,Male,Finance,61000,2021-02-25,Hyderabad
39,E040,Preethi,27.0,Female,Sales,52000,2022-04-18,Delhi
40,E041,Rahul,25.0,Male,IT,45000,2022-01-15,Bangalore
41,E042,Swetha,NaN,Female,HR,51000,2022-09-10,Chennai
42,E043,Dinesh,36.0,Male,Finance,78000,2018-11-14,Pune
43,E044,Aarti,28.0,Female,IT,55000,2021-07-23,Mumbai
44,E045,Prakash,40.0,Male,Sales,88000,2017-05-19,Delhi
45,E046,Monika,32.0,Female,Finance,67000,2020-10-08,Hyderabad
46,E047,Sunil,27.0,Male,IT,"57,000",2022-12-12,Bangalore
47,E048,Komal,29.0,Female,HR,49000,2023-02-28,Pune
48,E049,Raj,34.0,Male,Finance,73000,2019-06-17,Chennai
49,E050,Divya,30.0,Female,Sales,60000,2021-04-06,Delhi

In [ ]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   50 non-null     object
 1   Name          50 non-null     object
 2   Age           48 non-null     float64
 3   Gender        50 non-null     object
 4   Department    50 non-null     object
 5   Salary        49 non-null     object
 6   Joining_Date  50 non-null     object
 7   City          49 non-null     object
dtypes: float64(1), object(7)
memory usage: 3.3+ KB

In [ ]:
emp.isnull().sum()

Employee_ID     0
Name            0
Age             2
Gender          0
Department      0
Salary          1
Joining_Date    0
City            1
dtype: int64

# **Find WHICH rows have missing values**

In [ ]:
emp[emp.isnull().any(axis=1)]

   Employee_ID    Name   Age  Gender Department Salary Joining_Date       City
3         E004   Divya   NaN  Female    Finance  55000   2022-05-18  Hyderabad
4         E005   Kiran  26.0    Male         IT    NaN   2023-02-10     Mumbai
9         E010   Meena  30.0  Female      sales  61000   2021-06-25        NaN
41        E042  Swetha   NaN  Female         HR  51000   2022-09-10    Chennai

# **Check the median values first**

In [ ]:
"Median Age:", emp['Age'].median()

('Median Age:', 30.0)

 change the data type of sal beacuse currently data type of sal is object

In [ ]:
emp['Salary'] = pd.to_numeric(emp['Salary'], errors='coerce')

In [ ]:
emp['Salary'].median()

59500.0

In [ ]:
emp['Salary'] = emp['Salary'].fillna(59500)

In [ ]:
emp['Salary'].isnull().sum()

np.int64(0)

# **find median age**

In [ ]:
emp['Age'].median()

30.0

# **use that number**

In [ ]:
emp['Age'] = emp['Age'].fillna(30)

check

In [ ]:
emp['Age'].isnull().sum()

np.int64(0)

fix missing in city col

In [ ]:
emp['City'] = emp['City'].fillna('Unknown')

In [ ]:
emp['City'].isnull().sum()

np.int64(0)

Check all missing values

In [ ]:
emp.isnull().sum()

Employee_ID     0
Name            0
Age             0
Gender          0
Department      0
Salary          0
Joining_Date    0
City            0
dtype: int64

check for duplicates

In [ ]:
emp.duplicated().sum()

np.int64(0)

Check Department values

In [ ]:
emp['Department'].unique()

array(['IT', 'HR', 'it', 'Finance', 'Sales', 'sales', ' sales '],
      dtype=object)

Fix Department

In [ ]:
emp['Department'] = emp['Department'].str.strip()

In [ ]:
emp['Department'] = emp['Department'].replace({
    'it': 'IT',
    'sales': 'Sales',
    'Human Resources': 'HR'
})

In [ ]:
emp['Department'].unique()

array(['IT', 'HR', 'Finance', 'Sales'], dtype=object)

fix gender

In [ ]:
emp['Gender'].unique()

array(['Male', 'Female', 'female'], dtype=object)

In [ ]:
emp['Gender'] = emp['Gender'].replace({
    'female': 'Female'
})

In [ ]:
emp['Gender'].unique()

array(['Male', 'Female'], dtype=object)

Check all data types

In [ ]:
emp.dtypes

Employee_ID      object
Name             object
Age             float64
Gender           object
Department       object
Salary          float64
Joining_Date     object
City             object
dtype: object

Convert Joining_Date

In [ ]:
emp['Joining_Date'] = pd.to_datetime(emp['Joining_Date'])

In [ ]:
emp['Joining_Date'].dtype

dtype('<M8[ns]')

In [ ]:
emp.dtypes

Employee_ID             object
Name                    object
Age                    float64
Gender                  object
Department              object
Salary                 float64
Joining_Date    datetime64[ns]
City                    object
dtype: object

In [ ]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   50 non-null     object
 1   Name          50 non-null     object
 2   Age           50 non-null     float64
 3   Gender        50 non-null     object
 4   Department    50 non-null     object
 5   Salary        50 non-null     float64
 6   Joining_Date  50 non-null     datetime64[ns]
 7   City          50 non-null     object
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 3.3+ KB

Check missing values again

In [ ]:
emp.isnull().sum()

Employee_ID     0
Name            0
Age             0
Gender          0
Department      0
Salary          0
Joining_Date    0
City            0
dtype: int64

Check duplicates again

In [ ]:
emp.duplicated().sum()

np.int64(0)

Check inconsistent values

In [ ]:
print(emp['Department'].unique())
print(emp['Gender'].unique())

['IT' 'HR' 'Finance' 'Sales']
['Male' 'Female']

See the cleaned dataset

In [ ]:
emp.head(10)

,Employee_ID,Name,Age,Gender,Department,Salary,Joining_Date,City
0,E001,Rahul,25.0,Male,IT,45000.0,2022-01-15,Bangalore
1,E002,Priya,28.0,Female,HR,52000.0,2021-03-20,Chennai
2,E003,Arun,31.0,Male,IT,60000.0,2020-07-11,Bangalore
3,E004,Divya,30.0,Female,Finance,55000.0,2022-05-18,Hyderabad
4,E005,Kiran,26.0,Male,IT,59500.0,2023-02-10,Mumbai
5,E006,Sneha,29.0,Female,HR,48000.0,2021-09-05,Chennai
6,E007,Vikram,35.0,Male,Finance,72000.0,2019-11-22,Pune
7,E008,Anjali,27.0,Female,IT,58000.0,2022-08-14,Bangalore
8,E009,Rohit,33.0,Male,Sales,65000.0,2020-04-17,Delhi
9,E010,Meena,30.0,Female,Sales,61000.0,2021-06-25,Unknown

saving the cleaned dataset as a new CSV file.

In [ ]:
emp.to_csv('employee_salary_cleaned.csv', index=False)

In [ ]:
emp

,Employee_ID,Name,Age,Gender,Department,Salary,Joining_Date,City
0,E001,Rahul,25.0,Male,IT,45000.0,2022-01-15,Bangalore
1,E002,Priya,28.0,Female,HR,52000.0,2021-03-20,Chennai
2,E003,Arun,31.0,Male,IT,60000.0,2020-07-11,Bangalore
3,E004,Divya,30.0,Female,Finance,55000.0,2022-05-18,Hyderabad
4,E005,Kiran,26.0,Male,IT,59500.0,2023-02-10,Mumbai
5,E006,Sneha,29.0,Female,HR,48000.0,2021-09-05,Chennai
6,E007,Vikram,35.0,Male,Finance,72000.0,2019-11-22,Pune
7,E008,Anjali,27.0,Female,IT,58000.0,2022-08-14,Bangalore
8,E009,Rohit,33.0,Male,Sales,65000.0,2020-04-17,Delhi
9,E010,Meena,30.0,Female,Sales,61000.0,2021-06-25,Unknown
10,E011,Suresh,24.0,Male,IT,42000.0,2023-01-09,Bangalore
11,E012,Pooja,32.0,Female,Finance,68000.0,2020-12-01,Hyderabad
12,E013,Amit,29.0,Male,HR,50000.0,2022-03-12,Mumbai
13,E014,Neha,26.0,Female,IT,47000.0,2023-04-21,Pune
14,E015,Vijay,38.0,Male,Sales,85000.0,2018-10-30,Delhi
15,E016,Kavya,27.0,Female,Finance,59000.0,2022-07-19,Chennai
16,E017,Manoj,34.0,Male,IT,71000.0,2019-05-16,Bangalore
17,E018,Asha,23.0,Female,HR,43000.0,2023-06-08,Hyderabad
18,E019,Ramesh,41.0,Male,Finance,90000.0,2017-02-14,Pune
19,E020,Lakshmi,36.0,Female,Sales,76000.0,2019-08-27,Chennai
20,E021,Deepak,28.0,Male,IT,54000.0,2021-11-03,Mumbai
21,E022,Nisha,31.0,Female,HR,57000.0,2020-09-15,Bangalore
22,E023,Karthik,30.0,Male,Finance,63000.0,2021-01-20,Hyderabad
23,E024,Swathi,25.0,Female,IT,46000.0,2023-03-11,Pune
24,E025,Ajay,37.0,Male,Sales,79000.0,2019-12-05,Delhi
25,E026,Riya,29.0,Female,Finance,62000.0,2021-05-29,Chennai
26,E027,Naveen,33.0,Male,HR,59000.0,2020-02-18,Mumbai
27,E028,Shalini,27.0,Female,IT,51000.0,2022-10-07,Bangalore
28,E029,Ganesh,39.0,Male,Finance,82000.0,2018-06-13,Pune
29,E030,Isha,24.0,Female,Sales,44000.0,2023-07-02,Delhi
30,E031,Ravi,32.0,Male,IT,67000.0,2020-08-24,Bangalore
31,E032,Tina,30.0,Female,HR,56000.0,2021-10-19,Hyderabad
32,E033,Mohan,35.0,Male,Finance,74000.0,2019-03-09,Chennai
33,E034,Sonia,28.0,Female,IT,53000.0,2022-11-16,Mumbai
34,E035,Hari,42.0,Male,Sales,92000.0,2016-12-21,Delhi
35,E036,Rekha,26.0,Female,Finance,58000.0,2023-01-30,Pune
36,E037,Surya,31.0,Male,IT,64000.0,2020-06-05,Bangalore
37,E038,Maya,34.0,Female,HR,69000.0,2019-09-12,Chennai
38,E039,Nitin,29.0,Male,Finance,61000.0,2021-02-25,Hyderabad
39,E040,Preethi,27.0,Female,Sales,52000.0,2022-04-18,Delhi
40,E041,Rahul,25.0,Male,IT,45000.0,2022-01-15,Bangalore
41,E042,Swetha,30.0,Female,HR,51000.0,2022-09-10,Chennai
42,E043,Dinesh,36.0,Male,Finance,78000.0,2018-11-14,Pune
43,E044,Aarti,28.0,Female,IT,55000.0,2021-07-23,Mumbai
44,E045,Prakash,40.0,Male,Sales,88000.0,2017-05-19,Delhi
45,E046,Monika,32.0,Female,Finance,67000.0,2020-10-08,Hyderabad
46,E047,Sunil,27.0,Male,IT,59500.0,2022-12-12,Bangalore
47,E048,Komal,29.0,Female,HR,49000.0,2023-02-28,Pune
48,E049,Raj,34.0,Male,Finance,73000.0,2019-06-17,Chennai
49,E050,Divya,30.0,Female,Sales,60000.0,2021-04-06,Delhi

In [ ]:
emp[emp.duplicated(subset=['Name', 'Age', 'Gender', 'Department', 'Salary', 'Joining_Date', 'City'], keep=False)]

   Employee_ID   Name   Age Gender Department   Salary Joining_Date       City
0         E001  Rahul  25.0   Male         IT  45000.0   2022-01-15  Bangalore
40        E041  Rahul  25.0   Male         IT  45000.0   2022-01-15  Bangalore

In [ ]:
emp = emp.drop_duplicates(
    subset=['Name', 'Age', 'Gender', 'Department', 'Salary', 'Joining_Date', 'City']
)

In [ ]:
emp.shape

(49, 8)

In [ ]:
emp.isnull().sum()

Employee_ID     0
Name            0
Age             0
Gender          0
Department      0
Salary          0
Joining_Date    0
City            0
dtype: int64

In [ ]:
emp.duplicated().sum()

np.int64(0)